[package]
name = "fractured-ray"
version = "0.1.0"
edition = "2024"
authors = ["Justin Chen oosquare@outlook.com"]
description = "Minimal Raytracing Implementation"

[dependencies]
rand = "0.9.1"
snafu = "0.8.6"
